baseURL = "https://adajs.cat/gohugo-workshop-guide/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Hugo workshop - guide"
theme = "hugo-whisper-theme"
enableEmoji = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Guide"
    url = "/docs/"
    weight = 2

[params]
    homepage_image = "/images/screenshot-final.jpeg"
    [params.logo]
      standard = "/images/logo.png"
      mobile = "/images/logo.png"