baseURL = "https://adajs.cat/gohugo-workshop-guide/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Hugo workshop - guide"
theme = "hugo-whisper-theme"
enableEmoji = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Guide"
    url = "/docs/"
    weight = 2

[params]
    homepage_image = "/images/screenshot-final.png"
    homepage_button_link = "/docs"
    homepage_button_text = "Go to the guide"
    homepage_intro = "We are going to create a nice website for Momcorp (Futurama's robot company)"
    [params.logo]
      standard = "/images/logo.jpg"
      mobile = "/images/logo.jpg"