name: Publish Site

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Hugo
      uses: lowply/build-hugo@v0.58.3

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.1
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.GH_PAGES_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public