name: Publish Site

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Publish Site
        uses: chabad360/hugo-gh-pages@master
        with:
          hugoVersion: extended_0.58.3 # Ideally, keep this synced with your local version
          githubToken: ${{ secrets.GH_PAGES_KEY }}